### PR TITLE
modernize

### PR DESCRIPTION
**Pull request by ccutrer**
* apply rubocop (mostly layout, but a few style, lint, and param
   naming changes)
 * move gem executables to exe, so that bin can be used for bundler
   binstubs
 * remove deprecated methods
 * commit Gemfile.lock
 * add pre-commit config
 * add github actions to run rubocop and specs
 * remove travis

### CODE REVIEW

**Comment by ccutrer** [comment]
the actions ran in my fork (https://github.com/ccutrer/jar-dependencies/actions/runs/2602260281). after this is merged, then they'll run for PRs against this fork too

**Comment by enebo** [comment]
I think this should default on String literals and not force all of them to be "".  This is the default and the spirit of the original code.  It will also not create an extra hurdle when trying to look back in history since many lines will just show this style commit as last change.

I don't want to speak out of turn here either.  @mkristian what do you think?

**Comment by ccutrer** [comment]
Not a problem. I just copied some of my personal preferences from another project. As for history of bulk commits like this: https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt can help to some extent. Unfortunately the filename for it has not been standardized, so each developer has to configure it on their own machine. I've pushed up an amended commit, and also took out a few other customizations that didn't even apply to this codebase.

**Comment by headius** [comment]
There appears to be a bug here introduced by rubocop, fixed in df35d52616f9a1f425f596462b7bdfa64712ec03. This is the cause of at least https://github.com/ruby/rdoc/pull/1228 and possibly other user issues.

**Pull request merged**
