### PR TITLE
Use filename when calling eval

### PR DESCRIPTION
**Pull request by mfazekas**
Fixes: #42

### CODE REVIEW

**Comment by mfazekas** [comment]
i'd add a testcase but not sure where to put the gem folder demonstrating the issue.

**Comment by mkristian** [comment]
@mfazekas just under ./specs would be OK - as long the first three tests are green. still need to look what goes wrong with the last three tests on travis

**Comment by mfazekas** [comment]
@mkristian  even first 3 seems to be flaky i now cannot get them pass in one run:
this passes 3rd:
https://travis-ci.org/mkristian/jar-dependencies/builds/118788318
this passes 1 and 2nd
https://travis-ci.org/mkristian/jar-dependencies/builds/118791297

but no changes made

**Comment by mkristian** [comment]
@mfazekas yes flaky again and again . . . but thanks for the PR

**Pull request merged**
