### PR TITLE
slight tuning

### PR DESCRIPTION
**Pull request by kares**
... notes on IRC for the instance var warnings reminded me that I have some slight tunings around

I just forgot to commit and put those up in a PR ... hopefully some of it is useful, thanks!

### CODE REVIEW

**Comment by mkristian** [comment]
will remove 1.6.8 on travis - can not be bothered and it should work more or less on jruby-1.6.8 any ways.

thanx

**Comment by mkristian** [comment]
actually I tried to find those uninitialized instance variable warnings yesterday and never saw them. the only thing I got was an constant warning.

**Comment by kares** [comment]
thanks for the merge, related to uninitialized warnings ... maybe you did not run with the needed `-w/-W`

... did not notice the failures just know, as I was only running `rake specs` locally - there's an occasional (non-deterministic) failure at https://github.com/mkristian/jar-dependencies/blob/master/specs/classpath_spec.rb#L108 but it seems unrelated and seems to depend on load/spec order, not sure.

**Comment by mkristian** [comment]
yes, this 108 is well known. I spent quite some time end of last week to
get this spec not to fail so often, but I know it still fails occasionally
:(

thanx for the -w hint - never used this option and I was about to ask if
this uninitialized warning on instance variables is a new feature ;)

**Pull request merged**
