### PR TITLE
Fix code style for generated <gem>_jars.rb file

### LINKED ISSUE #61: Ruby style in generated <gem-name>_jars.rb
I just found some additional whitespace around arguments in the `require_jar` function that is called in the generated `lib/<gem-name>_jars.rb` file (assuming the gem use case).

It generates e.g. a file similar to this one:

```ruby
# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'nz/ac/waikato/cms/weka/thirdparty/java-cup-11b-runtime/2015.03.26/java-cup-11b-runtime-2015.03.26.jar'
end

if defined? Jars
  require_jar( 'nz.ac.waikato.cms.weka.thirdparty', 'java-cup-11b-runtime', '2015.03.26' )
end
```

The problem is that this is not the Ruby style recommended by the community (method calls should not have whitespace after/before parentheses) and the generated file fails to pass code linters such as Rubocop. Of course you can remove the whitespace manually, but you would have to do it by hand every time the file is regenerated.

Looks like the corresponding line of code is this one: https://github.com/mkristian/jar-dependencies/blob/d70197da81ccac4cc0b40e5ed29fd1c4b83be72c/lib/jars/installer.rb#L113

Do you mind if I open a PR to remove the extra whitespace?

### PR DESCRIPTION
**Pull request by paulgoetze**
Fixes #61.

I just removed the parentheses for all `require` and `require_jar` calls to keep it consistent and extended the regexes in the tests to match the full line.

### CODE REVIEW

**Comment by paulgoetze** [comment]
@mkristian Looks like there are issues with oraclejdk7 on Travis CI. Any ideas?

**Comment by mkristian** [comment]
@paulgoetze end of life reached :( - just remove it from .travis.yml

**Comment by mkristian** [comment]
the last test failure I saw before  and do not know where this comes from. but a restart worked :)

thanks. FYI try to cut a release soon but there is another open issue I really need to look at.

**Comment by paulgoetze** [comment]
:+1: Thanks @mkristian for the fast merging! Looking forward to the release once the other issue is resolved.

**Pull request merged**
